---
language: python
python:
    - '3.7'

before_install:
    - pip install poetry
install:
    - poetry config virtualenvs.create false
    - poetry config installer.parallel false
    - poetry install
script:
    - "invoke build"
    - "invoke tests"
